AWSTemplateFormatVersion: 2010-09-09
Description: Website on ryuichi.io

Resources:
  ContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'ryuichi.io'

  ContentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ContentBucket
      PolicyDocument:
        Id: PolicyForCloudFrontPrivateContent
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 's3:GetObject'
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}"
            Resource: !Sub "arn:aws:s3:::${ContentBucket}/*"

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'ryuichi.io domain to access its website contents'

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref ContentBucket
        DefaultCacheBehavior:
          ForwardedValues:
            Cookies:
              Forward: all
            QueryString: true
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
          TargetOriginId: ryuichi-io-content-bucket
          ViewerProtocolPolicy: https-only
        Enabled: true
        HttpVersion: http2
        Origins:
          - Id: ryuichi-io-content-bucket
            DomainName: !GetAtt ContentBucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
        DefaultRootObject: index.html
        PriceClass: PriceClass_200
        ViewerCertificate:
          AcmCertificateArn: 'arn:aws:acm:us-east-1:650892143834:certificate/539082de-dc06-43aa-a2a4-7a741279dfcb'
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
